"""從 YAML 規則生成 TypeScript 規則資料檔（P3-1）

用法：python scripts/generate_extension_rules.py
產出：extension/safety-guard-rules.ts

CI 檢查：generator 產出後 git diff --exit-code 確認無手動修改。
"""
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
RULES_DIR = ROOT / "src" / "skill_safety_guard" / "rules"
OUTPUT = ROOT / "extension" / "safety-guard-rules.ts"


def _escape_ts(s: str) -> str:
    """將正則字串轉義為 TS 字串字面量（\ → \\）"""
    return s.replace("\\", "\\\\")


def _gen_rules_array(var_name: str, yaml_file: str) -> str:
    """生成 TS 規則陣列"""
    data = yaml.safe_load((RULES_DIR / yaml_file).read_text(encoding="utf-8"))
    rules = data.get("rules", [])

    lines = [f"export const {var_name}: Rule[] = ["]
    for r in rules:
        rid = r.get("id", "")
        name = r.get("name", "")
        severity = r.get("severity", "medium")
        pattern = _escape_ts(r.get("pattern", ""))
        lines.append(f'  {{ id: "{rid}", name: "{name}", severity: "{severity}",')
        lines.append(f'    pattern: new RegExp("{pattern}") }},')
    lines.append("];")
    return "\n".join(lines)


def generate() -> None:
    """生成 safety-guard-rules.ts"""
    header = (
        "// AUTO-GENERATED by scripts/generate_extension_rules.py — DO NOT EDIT MANUALLY\n"
        "// Source: src/skill_safety_guard/rules/dangerous_shell.yaml + credentials.yaml\n"
        "// Regenerate: python scripts/generate_extension_rules.py\n"
        "\n"
        'export interface Rule {\n'
        '  id: string;\n'
        '  name: string;\n'
        '  pattern: RegExp;\n'
        '  severity: "critical" | "high" | "medium" | "low";\n'
        "}\n"
        "\n"
    )

    shell = _gen_rules_array("SHELL_RULES", "dangerous_shell.yaml")
    cred = _gen_rules_array("CRED_RULES", "credentials.yaml")

    content = header + shell + "\n\n" + cred + "\n"
    OUTPUT.write_text(content, encoding="utf-8")

    shell_count = len(
        yaml.safe_load((RULES_DIR / "dangerous_shell.yaml").read_text(encoding="utf-8"))["rules"]
    )
    cred_count = len(
        yaml.safe_load((RULES_DIR / "credentials.yaml").read_text(encoding="utf-8"))["rules"]
    )
    print(f"Generated {OUTPUT.name}: {shell_count} shell rules + {cred_count} cred rules")


if __name__ == "__main__":
    generate()
